### ISSUE TITLE
Question about Table 3

### ISSUE THREAD

**Issue by yukyunglee** [salesforce/dialog-flow-extraction#1]
Hello, thanks for sharing your great work! :)

I'd like to ask a question about Table 3.
When I run preprocess.py,
Attraction counts 150 instead of 135.

The results for the other domains are the same as in Table 3,
I'm wondering if there's something I missed or a typo.

Thank you

**Comment by Liang-Qiu** [comment]
@yukyunglee Hi, thank you for pointing that out!

I think I made a typo in the paper. I will correct it in the revised version.
